<?php
require_once(dirname(__FILE__) . '/resources/config.php');
require_once(dirname(__FILE__) . '/resources/lib/login-tools.php');
require_once(dirname(__FILE__) . '/resources/lib/database.php');
require_once($TEMPLATES_PATH . '/common.php');

html5_header(
	'Pending Requests',
	array('css/root.css', 'css/pending_requests.css'),
	array('js/pending_requests.js'));
	
html5_nav();

if ( is_logged_in() && isAdmin() ){
?>

    <!-- Pending adoptions -->
    <div class="pendingBox">
        <h2 class="title">Pending Adoptions</h2>
        <div class="pendingEntryBox" id="pendingAdoptions">
            <!-- entries to be generated by PHP, get pending entries from db -->
        </div>
    </div>

    <!-- Pending surrenders -->
    <div class="pendingBox">
        <h2 class="title">Pending Surrenders</h2>
        <div class="pendingEntryBox" id="pendingSurrenders">
            <!-- entries to be generated by PHP, get pending entries from db -->
        </div>
    </div>

<?php
} else { // end if admin
?>

<!-- this is just a safety precaution in case a user manually types in url to this page -->
    <div id="unauthorized">
        <p>Sorry, you are not authorized to view this page!</p>
    </div>

<?php
} // end if not admin

html5_footer();
?>